### ISSUE TITLE
Read method, return row object

### ISSUE THREAD

**Issue by nachoaguirre** [yuptogun/crud#1]
Hi, for the reading method, I added "row" as a possible parameter for $how, to get the result of 
a query with WHERE as an object.

Finally on the return switch I added
```
switch ($how) {
	case 'json':
		return json_encode($query->result_array());
		break;

	case 'array':
		return $query->result_array();
		break;
					
	case 'row':
		return $query->row();
		break;

	default:
		return $query->result();
		break;
	}
```

**Comment by yuptogun** [comment]
To be honest with you I'm not maintaining (or using by myself) this at all -- but this is really appreciated. Your suggestion will be applied soon, thanks!

PS. You can add limit option to get a single row by the way.
